server:
  port: 8080
  error:
    include-message: always
  spring:
    datasource:
      url: postgres://ffhlaxqyjdljsk:4cc497de2fb1b399d475116bd342651ce041e9c622b197ec2c25338b3fc628b1@ec2-52-212-228-71.eu-west-1.compute.amazonaws.com:5432/d661kh7qbtq4ad
      username: ffhlaxqyjdljsk
      password: 4cc497de2fb1b399d475116bd342651ce041e9c622b197ec2c25338b3fc628b1
      driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  sql:
    init:
      mode: always
  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 20MB
springdoc:
  swagger-ui:
    path: /swagger-ui.html

telegram_bot_username: sharp_0706_bot
telegram_bot_botToken: 5262928944:AAE9u_A7V-hzmoIjyih7KITN0vPvolfx5-w
#special_code: '+998909741228 +998332002022'



#https://matn.uz/


#https://matn.uz/


