server:
  port: 8080
  error:
    include-message: always
spring:
  datasource:
    url: postgres://fsstysxhtvsebp:ed852796c00f650bf533d2b3aad378408ba525c7a35eab51b91047600aa5e3cd@ec2-54-75-26-218.eu-west-1.compute.amazonaws.com:5432/da5v6ra9jhk40g
    username: fsstysxhtvsebp
    password: ed852796c00f650bf533d2b3aad378408ba525c7a35eab51b91047600aa5e3cd
    driver-class-name: org.postgresql.Driver
jpa:
  show-sql: true
  hibernate:
    ddl-auto: create
    defer-datasource-initialization: true
  properties:
    hibernate:
      enable_lazy_load_no_trans: true
  sql:
    init:
      mode: always
  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 20MB
springdoc:
  swagger-ui:
    path: /swagger-ui.html

telegram_bot_username: sharp_0706_bot
telegram_bot_botToken: 5262928944:AAE9u_A7V-hzmoIjyih7KITN0vPvolfx5-w

#special_code: '+998909741228 +998332002022'



#https://matn.uz/


#https://matn.uz/


