server:
  port: 8080
  error:
    include-message: always
spring:

  jackson:
    serialization:
      .fail-on-empty-beans: false
  datasource:
    url: jdbc:postgresql://localhost:5432/open_budget
    username: 'postgres'
    password: '0706'
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        enable_lazy_load_no_trans : true
  sql:
    init:
      mode: always
  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 20MB


telegram_bot_username: sharp_0706_bot
telegram_bot_botToken: 5262928944:AAE9u_A7V-hzmoIjyih7KITN0vPvolfx5-w
#special_code: '+998909741228 +998332002022'



#https://matn.uz/


#https://matn.uz/


